package com.yty.springcloud001consumer8080;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Springcloud002Consumer8080Application {

	public static void main(String[] args) {
		SpringApplication.run(Springcloud002Consumer8080Application.class, args);
	}

}
